version: '3'

services:
  postgres:
    image: postgres:11.8-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=cooperativism-db
      - POSTGRES_USER=cooperativism
      - POSTGRES_PASSWORD=cooperativism_ps
      - MAX_CONNECTIONS=300